### ISSUE TITLE
Doesn't boot

### ISSUE THREAD

**Issue by Degl1** [ValentinLiu15/android_kernel_xiaomi_alioth#1]
Have flashed this on numerous custom ROMs and it doesn't boot. Could it be firmware version dependant? Not sure how one would even debug it. Flashed the latest release on Codeberg.

**Comment by Degl1** [comment]
Built latest locally, still bootloops sadly.

**Comment by ValentinLiu15** [comment]
I'm really said for that. Could you provide more information?

Like your ROM name, Android version?

**Comment by Degl1** [comment]
Tried latest Codeberg release. Still no dice sadly.
Currently using latest StagOS Android 13, January 31st build. Might try a new ROM so will retry later.

**Comment by Degl1** [comment]
Update: my bad, flashed ArrowOS MIPA 11th March build and it works perfectly. Thanks for the kernel. Also about the kprofiles? Is it like any other, so 0=balanced, 1=battery, 2=performance.

**Comment by ValentinLiu15** [comment]
> Update: my bad, flashed ArrowOS MIPA 11th March build and it works perfectly. Thanks for the kernel. Also about the kprofiles? Is it like any other, so 0=balanced, 1=battery, 2=performance.

Yes, but now, the code from branch tenduo is belong to the "lmperf next" kernel project. I recommend you that use the code from tenduo at first.

The tenduo code has not kprofile code now, but i will add it later. Thank you for your support! Have a good day! :)

**Comment by ValentinLiu15** [comment]
And I highly recommend you trying to give me feedback at Codeberg. :)
