### ISSUE TITLE
自己编译的方案

### ISSUE THREAD

**Issue by zfdx123** [ValentinLiu15/android_kernel_xiaomi_alioth#2]
您好尊敬的开发者，我想自己编译这个内核，我clone您的代码库，然后用kernelsu的setup.sh 运行相关代码，但是编译结束只dtob和image没有办法生成lmperf.zip，请问可以在介绍中写一个完整的编译过程吗

**Comment by ValentinLiu15** [comment]
如果您使用的是自动脚本 /lmperf/build.sh 您需要将 AnyKernel3 放置到 /lmperf/package.sh 里写的目录。如果您使用命令行手动编译的话，则您需要自行打包

**Comment by zfdx123** [comment]
好的，谢谢您
