### ISSUE TITLE
求助：设备内部出现了问题

### ISSUE THREAD

**Issue by powerAn2020** [ValentinLiu15/android_kernel_xiaomi_alioth#5]
大佬，我clone代码后先执行了/lmperf/init.sh然后执行/lmperf/build.sh了，中间出现两次选择确认，都是默认回车，打出来的镜像刷入后提示开机出现【您的设备内部出现了问题，请联系你的制造商了解详情】，请教下您是如何打的包，我用Releases中的就没提示。

**Comment by zfdx123** [comment]
因为修改增加了配置文件内容，使得部分内核数据与官方不同，可以尝试修改配置文件来解决这个问题

**Comment by powerAn2020** [comment]
大佬，可否提示下修改的具体配置文件名，我去找下历史记录，纯小白，谢谢大佬。

**Comment by zfdx123** [comment]
alioth_lmperf_defconfig 默认配置文件是这个

**Comment by powerAn2020** [comment]
对不起，大佬，我太菜，看不懂，不知道改啥。。先用您提供的吧。

**Comment by ValentinLiu15** [comment]
修改 arch/arm64/config/alioth_lmperf_defconfig
MIUI系统有一个关于内核配置文件的 VTS 清单，将配置文件对照清单，修改重复的

**Comment by zfdx123** [comment]
已修復
